############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About this homepage"
pageRef = "/pages/about-this-hp.md"
weight = 2

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 3

# [[main]]
# name = "Categories"
# weight = 3

[[main]]
name = "Memo (External link)"
url = "https://sosuts.notion.site/f25413676d934f64bbbd4a7f03b452d5?pvs=74"
weight = 4

# [[main]]
# parent = "Categories"
# name = "Biology"
# pageRef = "/biology"

# [[main]]
# parent = "Categories"
# name = "CS"
# pageRef = "/cs"

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
